openapi: 3.2.0
info:
  contact: {}
  title: Groundwork Open Source Metric API
tags:
- name: Metric
paths:
  /metrics:
    get:
      description: The following API endpoint can be used to get list of metrics from the server.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        schema:
          type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
      tags:
      - Metric
      summary: Get metrics
      x-summary-source: derived
      operationId: getMetrics
      x-operation-id-source: derived
