openapi: 3.2.0
info:
  contact: {}
  title: Groundwork Open Source Downtimes API
tags:
- name: Downtimes
paths:
  /downtime-clear:
    post:
      description: The following API endpoint can be used to send Downtimes to Foundation.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        schema:
          type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      tags:
      - Downtimes
      summary: Create downtime clear
      x-summary-source: derived
      operationId: postDowntimeClear
      x-operation-id-source: derived
  /downtime-set:
    post:
      description: The following API endpoint can be used to send Downtimes to Foundation.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        schema:
          type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      tags:
      - Downtimes
      summary: Create downtime set
      x-summary-source: derived
      operationId: postDowntimeSet
      x-operation-id-source: derived
