openapi: 3.2.0
info:
  contact: {}
  title: Groundwork Open Source Agent API
tags:
- name: Agent
paths:
  /config:
    post:
      description: The following API endpoint can be used to Agent configure.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        schema:
          type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      tags:
      - Agent
      summary: Create config
      x-summary-source: derived
      operationId: postConfig
      x-operation-id-source: derived
  /identity:
    get:
      description: The following API endpoint can be used to get a TCG agent id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_gwos_tcg_sdk_transit.AgentIdentity'
      tags:
      - Agent
      summary: Get identity
      x-summary-source: derived
      operationId: getIdentity
      x-operation-id-source: derived
  /reset-nats:
    post:
      description: The following API endpoint can be used to reset NATS queues.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        schema:
          type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/services.ConnectorStatusDTO'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
      tags:
      - Agent
      summary: Create reset nats
      x-summary-source: derived
      operationId: postResetNats
      x-operation-id-source: derived
  /start:
    post:
      description: The following API endpoint can be used to start NATS dispatcher.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        schema:
          type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/services.ConnectorStatusDTO'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
      tags:
      - Agent
      summary: Create start
      x-summary-source: derived
      operationId: postStart
      x-operation-id-source: derived
  /stats:
    get:
      description: The following API endpoint can be used to get TCG statistics.
      parameters:
      - description: Auth header
        in: header
        name: gwos-app-name
        required: true
        schema:
          type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/services.AgentStatsExt'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      tags:
      - Agent
      summary: Get stats
      x-summary-source: derived
      operationId: getStats
      x-operation-id-source: derived
  /status:
    get:
      description: The following API endpoint can be used to get TCG status.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        schema:
          type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/services.ConnectorStatusDTO'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      tags:
      - Agent
      summary: Get status
      x-summary-source: derived
      operationId: getStatus
      x-operation-id-source: derived
  /stop:
    post:
      description: The following API endpoint can be used to stop NATS dispatcher.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        schema:
          type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/services.ConnectorStatusDTO'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
      tags:
      - Agent
      summary: Create stop
      x-summary-source: derived
      operationId: postStop
      x-operation-id-source: derived
  /version:
    get:
      description: The following API endpoint can be used to return actual TCG connector version.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        schema:
          type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/config.BuildInfo'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      tags:
      - Agent
      summary: Get version
      x-summary-source: derived
      operationId: getVersion
      x-operation-id-source: derived
components:
  schemas:
    expvar.Int:
      type: object
    services.AgentStatsExt:
      properties:
        agentId:
          type: string
        appName:
          type: string
        appType:
          type: string
        bytesSent:
          $ref: '#/components/schemas/expvar.Int'
        executionTimeInventory:
          $ref: '#/components/schemas/expvar.Int'
        executionTimeMetrics:
          $ref: '#/components/schemas/expvar.Int'
        lastErrors:
          items:
            $ref: '#/components/schemas/logzer.LogRecord'
          type: array
        lastEventsRun:
          $ref: '#/components/schemas/expvar.Int'
        lastInventoryRun:
          $ref: '#/components/schemas/expvar.Int'
        lastMetricsRun:
          $ref: '#/components/schemas/expvar.Int'
        messagesSent:
          $ref: '#/components/schemas/expvar.Int'
        metricsSent:
          $ref: '#/components/schemas/expvar.Int'
        upSince:
          $ref: '#/components/schemas/expvar.Int'
      type: object
    services.ConnectorStatusDTO:
      properties:
        connectorStatus:
          type: string
        jobId:
          type: integer
      type: object
    github_com_gwos_tcg_sdk_transit.AgentIdentity:
      properties:
        agentId:
          type: string
        appName:
          type: string
        appType:
          type: string
      type: object
    config.BuildInfo:
      properties:
        tag:
          type: string
        time:
          type: string
      type: object
    logzer.LogRecord:
      type: object
